# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/progen',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/progen',
                'lib_path': 'progen'},
  'syms': {'progen.core': {'progen.core.foo': ('core.html#foo', 'progen/core.py')}}}
