# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_tokenizer.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/02_tokenizer.ipynb 4
from transformers import AutoTokenizer
from datasets import load_dataset
