# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_tokenizer.ipynb.

# %% auto 0
__all__ = ['create_tokenizer']

# %% ../nbs/02_tokenizer.ipynb 4
from tokenizers import Tokenizer

# %% ../nbs/02_tokenizer.ipynb 5
def create_tokenizer(path = "../configs/tokenizer.json"):
    with open(path, "r") as f:
        tokenizer = Tokenizer.from_str(f.read())
    return tokenizer
