# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['ModelCheckpoint', 'download_checkpoint']

# %% ../nbs/00_utils.ipynb 4
class ModelCheckpoint:
    SMALL = "https://storage.googleapis.com/sfr-progen-research/checkpoints/progen2-small.tar.gz"
    MEDIUM = "https://storage.googleapis.com/sfr-progen-research/checkpoints/progen2-medium.tar.gz"
    LARGE = "https://storage.googleapis.com/sfr-progen-research/checkpoints/progen2-large.tar.gz"

# %% ../nbs/00_utils.ipynb 5
def download_checkpoint():
    pass
