name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test notebooks
      uses: fastai/workflows/nbdev-ci@master
    - name: Run pytest
      run: pytest -v
